services:
  postgres:
    image: postgres:17-alpine
    container_name: dealer_inventory_db
    environment:
      POSTGRES_DB: dealer_inventory
      POSTGRES_USER: dealer_user
      POSTGRES_PASSWORD: dealer_pass
    ports:
      - "5433:5432"
    volumes:
      - dealer_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dealer_user -d dealer_inventory"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dealer_pg_data:



